PELIMITER //

CREATE PROCEDURE SumTwoNumbers() BEGIN

PECLARE numI INT PEFAULT 10; DECLARE numz INT PEFAULT 20; PECLARE total INT;

SET total = numI + numz;

SELECT total AS Sum; END//

DELIMITER;

CALL SumTwoNumbers();
